### PR TITLE
Add support for versioned artifact names

### PR DESCRIPTION
**Pull request by sr55**
Add support for versioned artifact names

### CODE REVIEW

**Review by bradleysepos — APPROVED** [review]
Cool. 😸

Perhaps we can make the filenames `mingw-w64-build-$BUILD_VERSION-x86_64-linux.tar.gz` and `*-macos.tar.gz`?

**Comment by bradleysepos** [comment]
Also, while HandBrake only needs x86_64, would be nice to make i686 artifacts if it's just a copy and paste config for the most part.

**Comment by sr55** [comment]
Done and Done :)

**Comment by sr55** [comment]
Right, That should be things tidied up.

**Pull request merged**
